### ISSUE TITLE
Crowd scene randomly crashes when you render a sequence with mayabatch

### ISSUE THREAD

**Issue by xsisupport** [Autodesk/arnold-usd#1523] opened 2023-05-09 00:59 UTC
**Describe the bug**
Maya scene with usd procedural. usd procedural loads a crowd sim from Houdini. Render a sequence of frames (for example, render -r -s 1900 -e 1925) and the render crashes on one of the frames. Different frame each time you try.

**To Reproduce**
1. Contact support@arnoldrenderer.com for the repro scene
2. Do a command-line render of the maya scene file
3. Crash with no backtrace, just this:
```
00:01:29  1368MB         |  initializing 13 nodes
// Maya exited with status -1073740940
```

**Used Software Versions**
 - Arnold 7.2.1.1
 - Maya 2023.3, MtoA 5.2.1.1

**Comment by haggi** [comment] 2023-06-30 10:38
If it hels in any way: If I run in debug mode and attach the debugger to mayabatch.exe, then after rendering of some random number of frames I get this error c0000374 at the method **void
_SkelAdapter::_ComputeSkinningXforms(const UsdTimeCode time)** in the file **libs/translator/reader/read_skinning.cpp.**

**Comment by sebastienblor** [comment] 2024-03-15 11:00
Closing the ticket as the issue isn't reproducible anymore with USD 23.11

**Closed by sebastienblor** 2024-03-15 11:00 UTC
Labels: bug, user
