### ISSUE TITLE
ramp export/import bug at mtoa

### ISSUE THREAD

**Issue by chowooseoung** [Autodesk/arnold-usd#527] opened 2020-09-09 07:22 UTC
**Describe the bug**
The value is different when the ramp node is exported/imported. at mtoa

**To Reproduce**
1.create ramp, aiRampRgb
2. move selected position
3. arnold(maya memu) - operators - export operator graph(usd)
4. arnold(maya memu) - operators - import operator graph(usd)

**Expected behavior**
The moved value should come in.

**Screenshots**
If applicable, add screenshots to help expand your profile.
![saveRamp](https://user-images.githubusercontent.com/49386821/92566974-fc0f0080-f2b7-11ea-9756-3ae6381d56a7.png)
![importRamp](https://user-images.githubusercontent.com/49386821/92567260-658f0f00-f2b8-11ea-85f7-dc100cfbe47d.png)
```
#usda 1.0

def Shader "aiRampRgb1"
{
    uniform token info:id = "arnold:ramp_rgb"
    color3f[] inputs:color = [(0, 0, 0), (1, 1, 1)]
    int[] inputs:interpolation = [1, 1]
    string inputs:name = "aiRampRgb1"
    float[] inputs:position = [0.26086956, 0.35652173]
    string inputs:type = "v"
}

def Shader "ramp1"
{
    uniform token info:id = "arnold:ramp_rgb"
    color3f[] inputs:color = [(0, 0, 0), (1, 1, 1)]
    int[] inputs:interpolation = [1, 1]
    string inputs:name = "ramp1"
    float[] inputs:position = [0.2835249, 0.3869969]
    string inputs:type = "v"
    string inputs:use_implicit_uvs = "curves_only"
    bool inputs:wrap_uvs = 1
}
```

**Used Software Versions**
- OS: Linux
- mtoa 4.0.4
- maya 2019.2

**Additional context**
There was a problem with mtoa and I don't know if it's right to write here.

**Comment by sebastienblor** [comment] 2020-09-09 09:55
Thanks for reporting this !
This is indeed a MtoA problem. I could reproduce it also when exporting / importing to .ass.

I created a ticket in the MtoA tickets system https://trac.solidangle.com/mtoa/ticket/4322#ticket and I'll close this one, since it's not something that can be solved on the arnold-usd side.

Thanks

**Closed** 2020-09-09 09:55 UTC
Labels: bug
