### ISSUE TITLE
curves widths not translated if in timeSamples

### ISSUE THREAD

**Issue by dietchmatch** [Autodesk/arnold-usd#917] opened 2021-11-10 14:53 UTC
**Describe the bug**
We end up with
`// Error: [curves] .../groom_sphere: missing radius parameter`
on curves with widths defined with timeSamples

**To Reproduce**
simply kicking the attached usda files

**Expected behavior**
[timeSamples.zip](https://github.com/Autodesk/arnold-usd/files/7513585/timeSamples.zip)
the same as with the noTimeSamples usda

**Comment by sebastienblor** [comment] 2021-11-12 15:58
to be confirmed, but this seems to be fixed in Arnold 7.0.0.0
On my side I'm getting the same result with both usda files, with no errors in the timeSamples scene.

**Closed** 2021-11-16 07:53 UTC
Labels: bug
