### ISSUE TITLE
how to discover ndrArnold 

### ISSUE THREAD

**Issue by kreppene** [Autodesk/arnold-usd#86] opened 2019-11-29 09:50 UTC
its not clear to me how you would go about exporting arnold materials from maya to usd.

I compiled the arnold-usd (master branch) with this option enabled BUILD_USD_WRITER=True.
the compiler produced these 2 plugins as a result
> arnold-usd
>     plugin
>         hdArnold
>         ndrArnold

I also got the maya-usd (sandbox branch) compiled and running, the arnold render deligate is working, so the only missing part right now is how to go about exporting materials from maya.

Should it be possible to export arnold materials using the **pxrUsdExport** plugin, or is there som other way?

do i need to set this env variable ?
PXR_NDR_FS_PLUGIN_SEARCH_PATHS, if so where should it point?

i'm a bit lost here, so any insight is relay appreciated 

**My setup**
Windows 10
Maya 2019
Mtoa_3.3.0.2 /   Arnold 5.4.0.2

**Comment by sirpalee** [comment] 2019-11-29 10:07
Hey @kreppene , this is a duplicate of #30 . Closing this issue in favor of the original one.

**Closed by sirpalee** 2019-11-29 10:07 UTC
Labels: duplicate
