### ISSUE TITLE
Light barndoor behaviour has changed 

### ISSUE THREAD

**Issue by TomMinor** [Autodesk/arnold-usd#1654] opened 2023-09-06 16:54 UTC
**Describe the bug**
The light barndoor behaviour has changed recently, latest arnold-usd produces this
![image](https://github.com/Autodesk/arnold-usd/assets/5022079/7bd4184b-6aaa-4e74-8d17-4ac9e40aa1d7)

[arnold-usd@ced89a9](https://github.com/Autodesk/arnold-usd/commit/ced89a9) produces
![image](https://github.com/Autodesk/arnold-usd/assets/5022079/0ce59d14-47f2-45c7-b9ad-ceeba2f99a42)
[light_barndoor_example.zip](https://github.com/Autodesk/arnold-usd/files/12540506/light_barndoor_example.zip)

**To Reproduce**
I've attached an example usd file

**Expected behavior**

**Screenshots**

**Used Software Versions**
 - Arnold: 7.2.3.0
 - USD: [e.g. 0.19.11]
 - Compiler: [e.g. GCC 4.8.5]
 - OS: [e.g. MacOS 10.15]
 - Any 3rd-party app: Houdini 19.5.716

**Additional context**

**Comment by sebastienblor** [comment] 2023-09-18 15:55
the issue is actually on the HtoA side, closing as wontfix

**Closed as completed by sebastienblor** 2023-09-18 15:55 UTC
Labels: bug
