### ISSUE TITLE
Crash loading crowd usd file in the arnold procedural

### ISSUE THREAD

**Issue by jhodgson** [Autodesk/arnold-usd#472] opened 2020-07-01 09:28 UTC
Vincent Visca reports on the HtoA list:

 _If i try to load an .usd who contain a frame range with crowd through the procedural in houdini or maya, i got an instant crash if the viewport is activate ("Use file sequence" in maya). If i deactivate it, crash happen during the render._

In Houdini, adding an arnold_procedural OTL that referenced the USD file and setting the viewport proxy to file triggers the crash (this tries to load the USD procedural in a separate universe to generate a viewport representation).

**Comment by jhodgson** [comment] 2020-07-01 09:29
Adding hip file and usd file: [mocap.zip](https://github.com/Autodesk/arnold-usd/files/4856917/mocap.zip)

**Comment by jhodgson** [comment] 2020-07-07 14:17
From Vincent:

For curiosity, there is a warning each time i try to render a crowd, who look like :

/mocap/agent1_19/geometry/default_geo_skin/mesh_0: varying user-data count wrong! (found 37460 expected 9365) -- disabling user-data 'skel:jointIndices'

It not related to the frame range issue, but it can be reproduce with the file i sent previously.

**Comment by sirpalee** [comment] 2020-11-23 10:59
I ran a few tests on Linux, and the issue is gone in 20.08, but still crashes in 20.05. So upgrading the USD that the procedural is shipped with to 20.08 at least should solve this problem.

**Comment by sebastienblor** [comment] 2021-01-07 15:33
This is fixed with 20.08, we will upgrade the USD version used in the procedural in the next release. 
We can mark this issue as closed

**Closed by sebastienblor** 2021-01-07 15:33 UTC
Labels: bug, crash, procedural, upstream
