### ISSUE TITLE
Maya Arnold 7 Instanceable Not Rendering

### ISSUE THREAD

**Issue by brycegbrazen** [Autodesk/arnold-usd#1033] opened 2022-02-17 17:06 UTC
**Describe the bug**
Latest build of MtoA (5.0.0.3) with Arnold Core 7.0.0.2 seems to be unable to render prims if they are marked as USD Instanceable. Both prims with composition arcs (in this case Referencing) and prims with no composition arcs seem to be affected by this issue. Upon checking the USD Instanceable checkbox in Maya on the top level prim and saving the scene, the prims disappear from the Arnold render in Maya.

**To Reproduce**
1. Open the attached Maya file, this will have the USD file loaded as a stage.
[arnold7_instanceable_bug.zip](https://github.com/Autodesk/arnold-usd/files/8090689/arnold7_instanceable_bug.zip)
2. Please be aware the reference path the cube.usda will be mapped to **D:/arnold7**
2. Open the Arnold RenderView and render the scene.
3. Observe that both of the instanceable cubes are missing from the render. 

**Expected behavior**
I expect the USD Instanceable Prims to render in Arnold.

**Screenshots**
![Viewport](https://user-images.githubusercontent.com/69012021/154532866-3253fb0b-ced2-48f4-ae4a-f69a67bd7fa1.png)
![Arnold](https://user-images.githubusercontent.com/69012021/154532870-fc245d51-ea9a-44b9-90c2-fe3a1df896b2.png)

**Used Software Versions**
 - Arnold: 7.0.0.2
 - MtoA: 5.0.0.3
 - USD: 0.21.8
 - MayaUSD: v0.13.0
 - OS: Windows 10

**Additional context**
In the Maya script editor, I have sometimes seen this error appear:

// Error: [usd] Failed to open file () //

**Comment by BryceGattis** [comment] 2022-02-24 20:43
I would like to note, that removing the usd_cache_proc.dll file from the %ARNOLD_INSTALL_LOCATION%/extensions/usd/2108 (in a Python 3 context of 2022) seems to make the instanceable objects render again in Maya with no errors.

**Comment by sebastienblor** [comment] 2022-03-04 10:22
duplicate of #1050

**Closed by sebastienblor** 2022-03-04 10:22 UTC
Labels: bug
