### ISSUE TITLE
Improve AiOutputIteratorGetNext calls

### ISSUE THREAD

**Issue by AdrienHerubel** [Autodesk/arnold-usd#857] opened 2021-08-09 14:23 UTC
From an additional review on #845

> I took a look at the AiOutputIteratorGetNext change. If I understand the code properly, might I suggest cleaning the code by passing in a nullptr in render_delegate/nodes/driver_aov.cpp's usage since outputName doesn't seem to be used there? That should let you delete 5 lines of code.

> Then in the other file where it is used, you can replace all the strcmp with operator== on a statically built AtString.  I find that makes it easier to read and more importantly it's a tiny bit faster since AtString comparisons under the hood are just pointer comparisons.

**Comment by sirpalee** [comment] 2021-08-10 04:51
Closing as a duplicate of #856 . I also copied the comments here to that issue.

**Closed by sirpalee** 2021-08-10 04:51 UTC
Labels: duplicate
