### ISSUE TITLE
Crash in usdview on Frame (F) with Arnold renderer

### ISSUE THREAD

**Issue by BigRoy** [Autodesk/arnold-usd#76] opened 2019-11-28 07:40 UTC
**Describe the bug**

_I am not sure how to use `arnold-usd` yet exactly, see #68 so this could be an issue because of a wrong setup._

I tried loading up the example `triangle.ass` file into `usdview`. First I converted it to `triangle.usda` through `arnold_to_usd.exe`. Then I ran:
```
usdview --renderer Arnold /path/to/triangle.usda
```

Giving me:
![afbeelding](https://user-images.githubusercontent.com/2439881/69786259-5708b880-11ba-11ea-9417-3e06f0aa5f83.png)

The viewer opens but shows _nothing_ except for a bounding box and a gray background. Then when I press "F" to try and reframe the view it crashes:

```
> $ usdview --renderer Arnold D:\triangle.usda
WARNING |  GPU 0: GeForce GTX 650 Ti BOOST is unsupported
00:00:08  2245MB ERROR   |    signal caught: error C0000005 -- access violation

****
* Arnold 5.4.0.2 [30d7daaa] windows icc-17.0.2 oiio-2.1.0 osl-1.11.0 vdb-4.0.0 clm-1.0.3.513 rlm-12.4.2 optix-6.0.0 2019/10/09 17:19:01
* CRASHED in pxrInternal_v0_19__pxrReserved__::HdxPickTask::Sync at 00:00:00
* signal caught: error C0000005 -- access violation
*
* backtrace:
*  0 0x00007ff80b8b61ce [ai                          ]
*  1 0x00007ff80b8b546f [ai                          ]
*  2 0x00007ff87a8ff67a [KERNELBASE                  ] UnhandledExceptionFilter
*  3 0x00007ff87d044af2 [ntdll                       ] memset
*  4 0x00007ff87d02c6e6 [ntdll                       ] _C_specific_handler
*  5 0x00007ff87d04120f [ntdll                       ] _chkstk
*  6 0x00007ff87d00a299 [ntdll                       ] RtlRaiseException
*  7 0x00007ff87d03fe7e [ntdll                       ] KiUserExceptionDispatcher
>> 8 0x00007ff846da3e2a [libhdx                      ] pxrInternal_v0_19__pxrReserved__::HdxPickTask::Sync
*  9 0x00007ff846da224e [libhdx                      ] pxrInternal_v0_19__pxrReserved__::HdxPickResult::ResolveNearestToCenter
* 10 0x00007ff846da5724 [libhdx                      ] pxrInternal_v0_19__pxrReserved__::HdxPickFromRenderBufferTask::Execute
* 11 0x00007ff838558050 [libhd                       ] pxrInternal_v0_19__pxrReserved__::HdEngine::Execute
* 12 0x00007ff847f34f21 [libusdImagingGL             ] pxrInternal_v0_19__pxrReserved__::UsdImagingGLEngine::_Execute
* 13 0x00007ff847f34381 [libusdImagingGL             ] pxrInternal_v0_19__pxrReserved__::UsdImagingGLEngine::TestIntersection
* 14 0x00007ff84fad6b11 [_usdImagingGL               ] initlibusdImagingGL
* 15 0x00007ff84fad3aad [_usdImagingGL               ] initlibusdImagingGL
* 16 0x00007ff84fad64b1 [_usdImagingGL               ] initlibusdImagingGL
* 17 0x00007ff85621da05 [boost_python-vc141-mt-1_65_1] boost::python::objects::function::call
* 18 0x00007ff85621dd5a [boost_python-vc141-mt-1_65_1] boost::python::objects::function::get_namespace
* 19 0x00007ff8562235ef [boost_python-vc141-mt-1_65_1] boost::python::handle_exception_impl
* 20 0x00007ff85621bd7e [boost_python-vc141-mt-1_65_1] boost::python::objects::static_data
* 21 0x0000000052115283 [python27                    ] PyObject_Call
* 22 0x00007ff842c503f5 [libtf                       ] pxrInternal_v0_19__pxrReserved__::TfPyRunString
* 23 0x00007ff842c50271 [libtf                       ] pxrInternal_v0_19__pxrReserved__::TfPyRunString
* 24 0x00007ff85621da05 [boost_python-vc141-mt-1_65_1] boost::python::objects::function::call
* 25 0x00007ff85621dd5a [boost_python-vc141-mt-1_65_1] boost::python::objects::function::get_namespace
* 26 0x00007ff8562235ef [boost_python-vc141-mt-1_65_1] boost::python::handle_exception_impl
* 27 0x00007ff85621bd7e [boost_python-vc141-mt-1_65_1] boost::python::objects::static_data
* 28 0x0000000052115283 [python27                    ] PyObject_Call
* 29 0x00000000521c2f5b [python27                    ] PyEval_GetFuncDesc
* 30 0x00000000521c29f5 [python27                    ] PyEval_GetFuncDesc
* 31 0x00000000521bfe3b [python27                    ] PyEval_EvalFrameEx
* 32 0x00000000521c2b28 [python27                    ] PyEval_GetFuncDesc
* 33 0x00000000521c29df [python27                    ] PyEval_GetFuncDesc
* 34 0x00000000521bfe3b [python27                    ] PyEval_EvalFrameEx
* 35 0x00000000521c2b28 [python27                    ] PyEval_GetFuncDesc
* 36 0x00000000521c29df [python27                    ] PyEval_GetFuncDesc
* 37 0x00000000521bfe3b [python27                    ] PyEval_EvalFrameEx
* 38 0x00000000521c13b1 [python27                    ] PyEval_EvalCodeEx
* 39 0x00000000521c2b99 [python27                    ] PyEval_GetFuncDesc
* 40 0x00000000521c29df [python27                    ] PyEval_GetFuncDesc
* 41 0x00000000521bfe3b [python27                    ] PyEval_EvalFrameEx
* 42 0x00000000521c13b1 [python27                    ] PyEval_EvalCodeEx
* 43 0x00000000521c2b99 [python27                    ] PyEval_GetFuncDesc
* 44 0x00000000521c29df [python27                    ] PyEval_GetFuncDesc
* 45 0x00000000521bfe3b [python27                    ] PyEval_EvalFrameEx
* 46 0x00000000521c2b28 [python27                    ] PyEval_GetFuncDesc
* 47 0x00000000521c29df [python27                    ] PyEval_GetFuncDesc
* 48 0x00000000521bfe3b [python27                    ] PyEval_EvalFrameEx
* 49 0x00000000521c2b28 [python27                    ] PyEval_GetFuncDesc
* 50 0x00000000521c29df [python27                    ] PyEval_GetFuncDesc
* 51 0x00000000521bfe3b [python27                    ] PyEval_EvalFrameEx
* 52 0x00000000521c13b1 [python27                    ] PyEval_EvalCodeEx
* 53 0x000000005214a4e8 [python27                    ] PyFunction_SetClosure
* 54 0x0000000052115283 [python27                    ] PyObject_Call
* 55 0x000000005212a629 [python27                    ] PyMethod_New
* 56 0x0000000052115283 [python27                    ] PyObject_Call
* 57 0x000000018009ab9e [QtCore                      ]
* 58 0x0000000051e29cd3 [QtCore4                     ] QCoreApplicationPrivate::sendThroughApplicationEventFilters
* 59 0x0000000051082a8e [QtGui4                      ] QApplicationPrivate::notify_helper
* 60 0x0000000051084318 [QtGui4                      ] QApplication::notify
* 61 0x0000000004381558 [QtGui                       ]
* 62 0x0000000051e29c21 [QtCore4                     ] QCoreApplication::notifyInternal
* 63 0x00000000510ff67b [QtGui4                      ] qt_translateKeyCode
* 64 0x0000000051100857 [QtGui4                      ] qt_translateKeyCode
* 65 0x00000000510ea8b7 [QtGui4                      ] QApplication::restoreOverrideCursor
* 66 0x00007ff87b99681d [USER32                      ] CallWindowProcW
* 67 0x00007ff87b996212 [USER32                      ] DispatchMessageW
* 68 0x0000000051e550e5 [QtCore4                     ] QEventDispatcherWin32::processEvents
* 69 0x00000000510e8415 [QtGui4                      ] QApplicationPrivate::translateTouchEvent
* 70 0x0000000051e28c2f [QtCore4                     ] QEventLoop::exec
* 71 0x0000000051e2da60 [QtCore4                     ] QCoreApplication::exec
* 72 0x0000000004382882 [QtGui                       ]
* 73 0x00000000521c2779 [python27                    ] PyEval_GetFuncDesc
* 74 0x00000000521bfe3b [python27                    ] PyEval_EvalFrameEx
* 75 0x00000000521c2b28 [python27                    ] PyEval_GetFuncDesc
* 76 0x00000000521c29df [python27                    ] PyEval_GetFuncDesc
* 77 0x00000000521bfe3b [python27                    ] PyEval_EvalFrameEx
* 78 0x00000000521c2b28 [python27                    ] PyEval_GetFuncDesc
* 79 0x00000000521c29df [python27                    ] PyEval_GetFuncDesc
* 80 0x00000000521bfe3b [python27                    ] PyEval_EvalFrameEx
* 81 0x00000000521c13b1 [python27                    ] PyEval_EvalCodeEx
* 82 0x00000000521fdb50 [python27                    ] PyRun_FileExFlags
* 83 0x00000000521fdaba [python27                    ] PyRun_FileExFlags
* 84 0x00000000521fca7c [python27                    ] PyRun_SimpleFileExFlags
* 85 0x00000000521fc363 [python27                    ] PyRun_AnyFileExFlags
* 86 0x00000000520b7751 [python27                    ] Py_Main
* 87 0x000000001c7211ce [python                      ]
* 88 0x00007ff87bfa7bd4 [KERNEL32                    ] BaseThreadInitThunk
* 89 0x00007ff87d00cee1 [ntdll                       ] RtlUserThreadStart
*
* loaded modules:
*    0x00007ff80b560000  ai
*    0x00007ff87a800000  KERNELBASE
*    0x00007ff87cfa0000  ntdll
*    0x00007ff846d80000  libhdx
*    0x00007ff838540000  libhd
*    0x00007ff847f00000  libusdImagingGL
*    0x00007ff84fad0000  _usdImagingGL
*    0x00007ff856210000  boost_python-vc141-mt-1_65_1
*    0x0000000052060000  python27
*    0x00007ff842be0000  libtf
*    0x0000000180000000  QtCore
*    0x0000000051d10000  QtCore4
*    0x0000000051060000  QtGui4
*    0x0000000004340000  QtGui
*    0x00007ff87b980000  USER32
*    0x000000001c720000  python
*    0x00007ff87bf90000  KERNEL32
****
```

**To Reproduce**
1. Run `usdview -renderer Arnold /path/to/triangle.usda`
2. Press framing keyboard shortcut: `f`
3. Crash.

Files: [triangle.zip](https://github.com/Autodesk/arnold-usd/files/3900450/triangle.zip)

[The `triangle.ass` example file originates from Arnoldpedia](https://docs.arnoldrenderer.com/display/A5ARP/.ass+File+Examples)

**Expected behavior**
No crash, or a warning if I did something wrong.

**Used Software Versions**
 - Arnold: `5.4.0.2`
 - USD: `0.19.11`
 - Compiler: Visual Studio 2017
 - OS: Win 10
 - Any 3rd-party app: USD `usdview`

**Additional context**

My environment for `arnold_usd` (through `Rez`):
```py
# not sure what of these are actually needed
# {root} == compiled installation directory
    env.PATH.prepend("{root}/bin")
    env.LD_LIBRARY_PATH.prepend('{root}/lib/')  # unix
    env.PATH.prepend("{root}/lib")              # windows
    
    env.ARNOLD_PLUGIN_PATH.append("{root}/plugin")
    env.PATH.append("{root}/procedural")
    
    env.PYTHONPATH.append("{root}/lib/python")
    env.PXR_PLUGINPATH_NAME.append("{root}/plugin")
```

**Comment by sirpalee** [comment] 2019-11-28 10:46
What happens if you use the OpenGL renderer, HdStorm? After a quick glance at the stack trace, the render delegate is not involved. The top two entries in the stack trace are most likely the signal handlers installed by Arnold.

**Comment by sirpalee** [comment] 2019-11-28 11:26
I tried using USD 0.19.11 and the latest dev on Linux, but I was unable to reproduce the crash.

**Comment by BigRoy** [comment] 2019-11-28 14:25
I tried to reproduce it again now but am unable to get it to happen again in a similar way. Right when I thought "it must've been something else" however I had it happen.

The steps I took:

1. usdview -renderer Arnold /path/to/triangle.usda
2. View > Hydra Renderer > GL
3. View > Hydra Renderer > Arnold

Step 3 gave me this error:
```python
Traceback (most recent call last):
  File "D:\rez_packages\usd\19.11\platform-windows\PySide\lib\python\pxr\Usdviewq\appController.py", line 1321, in <lambda>
    self._rendererPluginChanged(pluginType))
  File "D:\rez_packages\usd\19.11\platform-windows\PySide\lib\python\pxr\Usdviewq\appController.py", line 1284, in _rendererPluginChanged
    if not self._stageView.SetRendererPlugin(plugin):
  File "D:\rez_packages\usd\19.11\platform-windows\PySide\lib\python\pxr\Usdviewq\stageView.py", line 955, in SetRendererPlugin
    if self._renderer.SetRendererPlugin(plugId):
pxr.Tf.ErrorException:
        Error in 'pxrInternal_v0_19__pxrReserved__::TfType::_DefineCppType' at line 937 in file D:\git_pipeline\rez-packages\usd\19.11\build\platform-windows\PySide\USD-19.11\pxr\base\lib\tf\type.cpp : 'TfType 'NdrArnoldDiscoveryPlugin' already has a defined C++ type; cannot redefine'
```
4. Then pressing "F" failed. 

However, then I wanted to reproduce that and I was unable to reproduce the error on step three. Now I'm not sure where this originates from.

**Comment by sirpalee** [comment] 2020-04-03 03:15
I'm going to close this as we were never able to reproduce this particular one. If you are still getting crashes when framing a selection on newer USD versions, please create a new issue.

**Closed by sirpalee** 2020-04-03 03:15 UTC
Labels: bug, investigate, render delegate
