### ISSUE TITLE
Hydra delegate does not render motion blur after you move camera

### ISSUE THREAD

**Issue by xsisupport** [Autodesk/arnold-usd#1844] opened 2024-02-05 18:23 UTC
**Describe the bug**
If you move the camera, motion blur disappears.

**To Reproduce**
1. Load the attached usd file into UsdView (or Houdini Solaris)
[helix_motionblur.usd_rop1.usda.zip](https://github.com/Autodesk/arnold-usd/files/14169973/helix_motionblur.usd_rop1.usda.zip)

2. Render with Arnold
3. Move the camera. The motion blur disappears.
4. You have to force a full update to get the motion blur back.

**Expected behavior**

**Screenshots**
![arnold-usd-motion-blur](https://github.com/Autodesk/arnold-usd/assets/3514355/5f571979-be31-4d34-bcf3-f685883aa435)

**Used Software Versions**
 - Houdini 20, HtoA 6.2.5.1

**Comment by xsisupport** [comment] 2024-02-12 14:50
I don't know. I can repro it in Houdini too.

**Comment by BigRoy** [comment] 2024-02-15 22:59
> I don't know. I can repro it in Houdini too.

Can confirm - reproducable in HtoA 6.2.5.2

**Comment by cpichard** [comment] 2024-02-16 10:54
I tested in HTOA, when editing a scene camera, the motion blur disappear when it shouldn't. This due to the arnold camera being re-created at every camera parameter change plus the shutter parameters not correctly set after the re-creation. 
It is fixed by #1855 which should land in the next bug fix release, I double checked in the htoa dev version.

**Comment by BigRoy** [comment] 2024-02-16 11:19
> change plus the shutter parameters not correctly set after the re-creation

Would that mean that even with #1855 that if a user were to change the "shutter start" and "shutter end" in Houdini Solaris while the render is in progress that it doesn't update - since that 'set shutter start/end on update' didn't work? Or did it just fail to set it on the new camera since it didn't get any notifications on "Shutter start/end changed" and thus didn't re-apply it.

Anyway, sounds like the camera sync fix might just solve quite a few issues!

**Comment by cpichard** [comment] 2024-02-27 03:38
Changing the shutter would work now as the camera is not recreated.

**Comment by sebastienblor** [comment] 2024-03-01 07:55
Closing the ticket since it was fixed by #1855

**Closed** 2024-03-01 10:04 UTC
Labels: bug
