### ISSUE TITLE
Add support for shader output property in ndrArnold parser

### ISSUE THREAD

**Issue by frenchdog** [Autodesk/arnold-usd#757] opened 2021-04-17 00:36 UTC
**Describe the feature you'd like**
Ability to get information about an Arnold node output when querying an SdrShaderNode.

**Describe the solution you'd like**
Since an Arnold node output does not have an explicit name, calling NdrNode::GetOutputNames() would return a vector with only one "out" string.
Calling SdrShaderNode::GetShaderOutput("out") would return a valid SdrShaderProperty.
Such property would give information like its type and if it is an array.

**Additional context**
Such feature would allow to write generic code for applications using the NdrDiscoveryPlugin mechanism to create shader nodes.

**Comment by sebastienblor** [comment] 2022-08-17 14:57
duplicate of #1211

**Closed** 2022-08-17 14:56 UTC
Labels: enhancement
