### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by furby-tm** [Autodesk/arnold-usd#149] opened 2020-01-14 00:27 UTC
**Describe the bug**
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 4: invalid start byte
```
This bug occurs when attempting to run the build with python 3.7 and Arnold 6. Seems like there needs to be a way to check utf codecs.

The schema generated is the following:
```
#usda 1.0
(
"This file describes the Arnold USD schemas."
    subLayers = [
        @usd/schema.usda@,
        @usdGeom/schema.usda@,
        @usdShade/schema.usda@,
        @usdLux/schema.usda@
    ]
)
over "GLOBAL" (
    customData = {
        string libraryName = "usdArnold"
        string libraryPath = "./"
        string libraryPrefix = "Usd"
        string tokensPrefix = "UsdArnold"
    }
) {
}
class ArnoldCamera "ArnoldCamera"(
    inherits = [</Camera>]
) {
    vector3f[] position
    vector3f[] look_at
    vector3f[] up
    matrix4d[] matrix
```
And thus it stops here:
```
	Error in 'textFileFormatYyerror' at line 3111 in file pxr/usd/sdf/textFileFormat.yy : 'syntax error at '' in </ArnoldCamera> on line 27 in file /home/furby/arnold-usd/build/linux_x86_64/gcc_opt/usd-0.19.7_arnold-6.0.1.0/schemas/schema.usda
```

**Comment by sirpalee** [comment] 2020-01-15 10:56
Arnold-USD explicitly requires Python 2.7, and unless USD/master supports Python 3+ we need to stick to 2.7 version.

I'm marking the issue blocked until USD moves forward with its python version.

**Comment by sirpalee** [comment] 2020-02-13 22:35
Since we are moving to cmake, meaning there is less python code to modify for python3, I'm unblocking this ticket.

@tyler-furby could you please give me more information about how you are building USD and Arnold - USD in your setup, so I can try to reproduce your problem locally? Last time I checked USD itself, it looked pretty much hardcoded to python 2.7 (some of the cmake scripts). Was that an incorrect assumption or you have local modifications?

**Comment by tyler-furby** [comment] 2020-02-13 22:46
I locally modified it to move it over to Python 3. I believe it has to do with utf encoding issues with the `AtPythonString` in the Arnold SDK Python's `ai_types.py` file.

**Comment by furby-tm** [comment] 2020-12-04 03:14
@sirpalee Hey there, how's it going? Went to go build the delegate and it appears the python build is still set for python 2. I presume for building on python 3 we're going full cmake? 

How well rounded out is the python 3 version of the delegate?

**Comment by sirpalee** [comment] 2020-12-04 05:23
Hi @furby-tm, yes, correct, both the scons and the cmake build system are python 2. Otherwise, none of the compiled plugins are explicitly using python, except the python bindings for the schemas, so everything should work just fine independently of which python you used to build USD.

Let's move the discussion to #509. I know it's an older ticket with no activity, but knowing your needs helps us deciding what to tackle next.

**Comment by cpichard** [comment] 2024-02-16 11:27
Closing as arnold-usd is now compatible with python 3.

**Closed by cpichard** 2024-02-16 11:27 UTC
Labels: bug, build, user
