### ISSUE TITLE
Primvars is ignored when rendering basisCurves as bspline

### ISSUE THREAD

**Issue by kreppene** [Autodesk/arnold-usd#854] opened 2021-08-06 10:54 UTC
**Describe the bug**
When rendering BasisCurves using basis bspline, the primvars is ignored. and we get messages like this

```
/Root/RootOffset/g_geometry/groom/my_nice_groom/my_nice_groomShape: varying user-data count wrong! (found 651014 expected 550858) -- disabling user-data 'look_color'

/Root/RootOffset/g_geometry/groom/my_nice_groom/my_nice_groomShape: varying user-data count wrong! (found 651014 expected 550858) -- disabling user-data 'look_tip'
```

**To Reproduce**
1. Extract the attached zip file
2. Edit the .ass file and update the path to the usdfile (currently its pointing to my local harddriver)
3. kick -l ../shaders -l ../procedurals -l ../plugins C:/qvisten_pipeline/primvarsBug/renderme.ass

**Expected behavior**
If the primvars is working fine when rendering the BasisCruves using linear basis, it should also work when using bspline basis

**Screenshots**
render trough the arnold procedural  basis bspline
![image](https://user-images.githubusercontent.com/7374105/128498508-5e1c0203-f833-40bf-ae46-6fbdf46508b2.png)

Render trough the arnold procedural  basis linear
![image](https://user-images.githubusercontent.com/7374105/128498574-42e3778c-4578-4462-ba0f-0c6166f0c3be.png)

Rendered with Arnold Hydra in solaris
![image](https://user-images.githubusercontent.com/7374105/128497056-0c3ce733-b1a5-4050-9403-13c172cd7ce2.png)

**Used Software Versions**
 - Arnold: 6.2.1.1
 - OS: windows 10
 - Maya 2022.1

**Additional context**
[primvarsBug.zip](https://github.com/Autodesk/arnold-usd/files/6945016/primvarsBug.zip)

**Comment by sebastienblor** [comment] 2021-11-16 07:56
looks like #921 was a duplicate of this ticket

**Closed** 2021-11-16 09:41 UTC
Labels: bug
